export const PractitionerTypes = {
    GET_PRACTITIONERS_SUCCESS: 'GET_PRACTITIONERS_SUCCESS',
    GET_PRACTITIONERS_PENDING: 'GET_PRACTITIONERS_PENDING',
    GET_PRACTITIONERS_ERROR: 'GET_PRACTITIONERS_ERROR'  
}