export const allPractitioners = [
    {
      "id": { "$oid": "5ed51150fc13ae16c5000000" },
      "name": "Krissie Dutton",
      "image": "https://images.pexels.com/photos/3714743/pexels-photo-3714743.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      "email": "kdutton0@youtu.be",
      "location": "Baume-les-Dames",
      "lat": 47.343506,
      "lng": 6.309262,
      "phone": "136-970-6999",
      "degree": "Lithunian Academy of Music and Theatre",
      "specialty": "Surgeon",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$87.70"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000001" },
      "name": "Tory Canlin",
      "image": "https://images.pexels.com/photos/3825434/pexels-photo-3825434.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      "email": "tcanlin1@desdev.cn",
      "location": "Putina",
      "lat": -14.91256,
      "lng": -69.874893,
      "phone": "694-325-3634",
      "degree": "Universidad San Juan de la Cruz",
      "specialty": "Allergist",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$84.50"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000002" },
      "name": "Ivonne Celes",
      "image": "https://image.shutterstock.com/image-photo/portrait-happy-african-man-doctor-260nw-1287649663.jpg",
      "email": "iceles2@pagesperso-orange.fr",
      "location": "Mina Clavero",
      "lat": -31.730594,
      "lng": -65.006098,
      "phone": "198-532-8690",
      "degree": "Chatham College",
      "specialty": "Surgeon",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$72.21"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000003" },
      "name": "Bertrando Dossetter",
      "image": "https://image.shutterstock.com/image-photo/african-american-doctor-good-news-260nw-1273867657.jpg",
      "email": "bdossetter3@dmoz.org",
      "location": "Makoko",
      "lat": 6.4990277,
      "lng": 3.3880288,
      "phone": "182-167-4297",
      "degree": "University of East Srarajevo",
      "specialty": "Allergist",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$85.87"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000004" },
      "name": "Bobine Zaczek",
      "image": "https://image.shutterstock.com/image-photo/studio-shot-young-handsome-african-260nw-777510475.jpg",
      "email": "bzaczek4@hibu.com",
      "location": "Bełżec",
      "lat": 50.384945,
      "lng": 23.438111,
      "phone": "109-572-8278",
      "degree": "Baker College of Port Huron",
      "specialty": "Surgeon",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$93.72"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000005" },
      "name": "Nehemiah Shipsey",
      "image": "https://image.shutterstock.com/image-photo/handsome-nigerian-doctor-smiling-260nw-1521359189.jpg",
      "email": "nshipsey5@earthlink.net",
      "location": "Shitong",
      "lat": 30.025924,
      "lng": 121.166112,
      "phone": "582-619-8692",
      "degree": "Ohka Gakuen University",
      "specialty": "Allergist",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$26.40"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000006" },
      "name": "Lacey Casemore",
      "image": "https://image.shutterstock.com/image-photo/studio-shot-young-handsome-african-260nw-764932744.jpg",
      "email": "lcasemore6@infoseek.co.jp",
      "location": "Wangren",
      "lat": 30.150684,
      "lng": 115.134207,
      "phone": "248-277-8975",
      "degree": "South-East Asia University",
      "specialty": "Surgeon",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$25.49"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000007" },
      "name": "Corbin Parkman",
      "image": "https://image.shutterstock.com/image-photo/african-doctor-looking-radiography-260nw-95090179.jpg",
      "email": "cparkman7@army.mil",
      "location": "Kumberg",
      "lat": 47.2173146,
      "lng": 15.6237211,
      "phone": "532-362-7493",
      "degree": "Knowledge International University",
      "specialty": "Cancer Surgeon",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$46.26"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000008" },
      "name": "Kassia Jeandel",
      "image": "https://image.shutterstock.com/image-photo/studio-shot-young-african-man-260nw-766407142.jpg",
      "email": "kjeandel8@wsj.com",
      "location": "Kolno",
      "lat": 53.4077753,
      "lng": 21.9326485,
      "phone": "989-312-9594",
      "degree": "Sinnar University",
      "specialty": "Surgeon",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$83.22"
    },
    {
      "id": { "$oid": "5ed51150fc13ae16c5000009" },
      "name": "Virginie Rawson",
      "image": "https://image.shutterstock.com/image-photo/happy-confident-african-american-medical-260nw-1720372186.jpg",
      "email": "vrawson9@hc360.com",
      "location": "Takahashi",
      "lat": 38.632511,
      "lng": 140.4875299,
      "phone": "436-741-0910",
      "degree": "Bartlesville Wesleyan College",
      "specialty": "Cancer Surgeon",
      "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
      "fees": "$38.06"
    },
    {
        "id": { "$oid": "5ed5163cfc13ae73b2000000" },
        "name": "Hermina Gwinn",
        "image": "https://image.shutterstock.com/image-photo/young-african-american-doctor-isolated-260nw-55154536.jpg",
        "email": "hgwinn0@unicef.org",
        "location": "Airuk",
        "lat": 7.068209,
        "lng": 171.281541,
        "phone": "557-305-5707",
        "degree": "Federal Polytechnic Bauchi, Nigeria",
        "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
        "fees": "$88.99",
        "specialty": "Gynaecologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000001" },
        "name": "Bone Frazier",
        "image": "https://image.shutterstock.com/image-photo/africanamerican-doctor-on-white-background-260nw-1696435960.jpg",
        "email": "bfrazier1@geocities.com",
        "location": "Mount Frere",
        "lat": -27.990857,
        "lng": 26.724185,
        "phone": "320-955-7593",
        "degree": "Universidad Católica San Antonio",
        "biography": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
        "fees": "$76.07",
        "specialty": "Gynaecologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000002" },
        "name": "Abigail Grunwald",
        "image": "https://image.shutterstock.com/image-photo/africanamerican-black-doctor-man-on-260nw-313359950.jpg",
        "email": "agrunwald2@cornell.edu",
        "location": "Al Qadmūs",
        "lat": 35.1008082,
        "lng": 36.1613289,
        "phone": "820-101-0768",
        "degree": "University of North Carolina at Asheville",
        "biography": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
        "fees": "$46.06",
        "specialty": "Gynaecologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000003" },
        "name": "Son Durie",
        "image": "https://image.shutterstock.com/image-photo/closeup-portrait-friendly-smiling-confident-260nw-188195045.jpg",
        "email": "sdurie3@delicious.com",
        "location": "Hezhai",
        "lat": 35.23375,
        "lng": 115.480656,
        "phone": "584-229-0916",
        "degree": "Panjab University",
        "biography": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
        "fees": "$50.65",
        "specialty": "Cardiologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000004" },
        "name": "Avram Cardenas",
        "image": "https://image.shutterstock.com/image-photo/portrait-female-doctor-holding-her-260nw-1036503502.jpg",
        "email": "acardenas4@facebook.com",
        "location": "Andrijevica",
        "lat": 42.7362477,
        "lng": 19.7859556,
        "phone": "975-114-1869",
        "degree": "Universitas Darma Agung",
        "biography": "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
        "fees": "$86.72",
        "specialty": "Cardiologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000005" },
        "name": "Jeth Postlethwaite",
        "image": "https://image.shutterstock.com/image-photo/african-american-chief-physician-medical-260nw-1296865456.jpg",
        "email": "jpostlethwaite5@independent.co.uk",
        "location": "Quillabamba",
        "lat": -12.868355,
        "lng": -72.6919814,
        "phone": "999-498-0343",
        "degree": "St. Luke' s College of Nursing",
        "biography": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
        "fees": "$55.33",
        "specialty": "Cardiologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000006" },
        "name": "Cory Hadwen",
        "image": "https://image.shutterstock.com/image-photo/professional-african-american-doctor-hospital-260nw-1453382393.jpg",
        "email": "chadwen6@si.edu",
        "location": "Bensonville",
        "lat": 6.446976,
        "lng": -10.6182477,
        "phone": "706-936-7466",
        "degree": "Universidad Arcis",
        "biography": "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
        "fees": "$68.42",
        "specialty": "Radiologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000007" },
        "name": "Bettye Bartalucci",
        "image": "https://image.shutterstock.com/image-photo/young-african-doctor-isolated-over-260nw-1684672057.jpg",
        "email": "bbartalucci7@odnoklassniki.ru",
        "location": "Songzhuang",
        "lat": 39.964054,
        "lng": 116.714967,
        "phone": "338-406-7417",
        "degree": "Ecole Supérieure de Commerce de Dijon",
        "biography": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
        "fees": "$38.01",
        "specialty": "Radiologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000008" },
        "name": "Hodge McGrath",
        "image": "https://image.shutterstock.com/image-photo/portrait-young-female-african-doctor-260nw-1554193814.jpg",
        "email": "hmcgrath8@blog.com",
        "location": "Duszniki-Zdrój",
        "lat": 50.404284,
        "lng": 16.3904406,
        "phone": "477-589-1632",
        "degree": "John F. Kennedy University",
        "biography": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
        "fees": "$43.74",
        "specialty": "Radiologist"
      },
      {
        "id": { "$oid": "5ed5163cfc13ae73b2000009" },
        "name": "Page Wheble",
        "image": "https://image.shutterstock.com/image-photo/doctor-mask-black-man-african-260nw-1698963193.jpg",
        "email": "pwheble9@boston.com",
        "location": "Puerto Plata",
        "lat": 19.7553444,
        "lng": -70.8233213,
        "phone": "439-674-8473",
        "degree": "Universitas Katolik Soegijapranoto",
        "biography": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
        "fees": "$42.37",
        "specialty": "Midwife"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e000003" },
        "name": "Lindy Niessen",
        "image": "https://image.shutterstock.com/image-photo/medicine-profession-healthcare-concept-happy-260nw-1669772809.jpg",
        "email": "lniessen0@i2i.jp",
        "location": "Krông Kmar",
        "lat": 12.5075773,
        "lng": 108.3356312,
        "phone": "486-839-3545",
        "degree": "Privredna Akademija (Business Academy)",
        "biography": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
        "fees": "$84.74",
        "specialty": "Orthopedist"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e000004" },
        "name": "Charity Schinetti",
        "image": "https://image.shutterstock.com/image-photo/black-female-physician-prescribing-pills-260nw-342696572.jpg",
        "email": "cschinetti1@delicious.com",
        "location": "Grzmiąca",
        "lat": 53.8508917,
        "lng": 16.4443227,
        "phone": "823-522-8087",
        "degree": "Universidad la Concordia",
        "biography": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
        "fees": "$75.78",
        "specialty": "Orthopedist"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e000005" },
        "name": "Carole Lighten",
        "image": "https://image.shutterstock.com/image-photo/pretty-african-american-nurse-pointing-260nw-151306736.jpg",
        "email": "clighten2@businesswire.com",
        "location": "Gombong",
        "lat": -7.6052823,
        "lng": 109.5151561,
        "phone": "438-925-7840",
        "degree": "Universitas Katolik Soegijapranoto",
        "biography": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
        "fees": "$45.12",
        "specialty": "Andrologist"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e000006" },
        "name": "Ricky Evershed",
        "image": "https://image.shutterstock.com/image-photo/smiling-doctor-sitting-table-his-260nw-346218035.jpg",
        "email": "revershed3@photobucket.com",
        "location": "Juazeiro do Norte",
        "lat": -7.2284727,
        "lng": -39.3121233,
        "phone": "447-692-0122",
        "degree": "Jamestown College",
        "biography": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        "fees": "$87.06",
        "specialty": "Andrologist"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e000007" },
        "name": "Alic Feaver",
        "image": "https://image.shutterstock.com/image-photo/portrait-handsome-smiling-doctor-260nw-256955077.jpg",
        "email": "afeaver4@foxnews.com",
        "location": "Quán Hàu",
        "lat": 17.4044214,
        "lng": 106.6379724,
        "phone": "537-657-5736",
        "degree": "Afyon Kocatepe University",
        "biography": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
        "fees": "$87.12",
        "specialty": "Urologist"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e000008" },
        "name": "Tabor Anfonsi",
        "image": "https://image.shutterstock.com/image-photo/confident-look-cheerful-professional-doctor-260nw-1141444853.jpg",
        "email": "tanfonsi5@berkeley.edu",
        "location": "Lamawan",
        "lat": 40.081331,
        "lng": 111.395534,
        "phone": "430-368-0983",
        "degree": "Gediz University",
        "biography": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
        "fees": "$56.41",
        "specialty": "Urologist"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e000009" },
        "name": "Ileane Gold",
        "image": "https://image.shutterstock.com/image-photo/studio-shot-young-handsome-african-260nw-777510475.jpg",
        "email": "igold6@mayoclinic.com",
        "location": "Jambeyan",
        "lat": -7.646682,
        "lng": 110.6064632,
        "phone": "303-884-3743",
        "degree": "New England Institute of Technology",
        "biography": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
        "fees": "$30.14",
        "specialty": "Dentist"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e00000a" },
        "name": "Alvan Giggie",
        "image": "https://image.shutterstock.com/image-photo/portrait-african-doctor-stethoscope-around-260nw-771883645.jpg",
        "email": "agiggie7@ifeng.com",
        "location": "Villa Bustos",
        "lat": -31.2657738,
        "lng": -64.460387,
        "phone": "711-258-0096",
        "degree": "National Institute of Education",
        "biography": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
        "fees": "$27.72",
        "specialty": "Dentist"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e00000b" },
        "name": "Nita Richings",
        "image": "https://image.shutterstock.com/image-photo/young-african-american-doctor-man-260nw-1206831514.jpg",
        "email": "nrichings8@youku.com",
        "location": "Golema Rečica",
        "lat": 41.98803,
        "lng": 20.94517,
        "phone": "799-890-2624",
        "degree": "Dalian University",
        "biography": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
        "fees": "$82.02",
        "specialty": "General Practitioner"
      },
      {
        "id": { "$oid": "5ed518d6fc13ae4b3e00000c" },
        "name": "Laurence Argrave",
        "image": "https://image.shutterstock.com/image-photo/cheerful-young-black-physician-stethoscope-260nw-1707814660.jpg",
        "email": "largrave9@clickbank.net",
        "location": "Dazhangzhuang",
        "lat": 32.979258,
        "lng": 114.890194,
        "phone": "284-619-4447",
        "degree": "Donghua University, Shanghai",
        "biography": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
        "fees": "$33.98",
        "specialty": "General Practitioner"
      }
      
  ]
  